### ISSUE TITLE
Advanced Usage in Phoenix.View no longer works

### ISSUE THREAD

**Issue by bendyorke** [DefactoSoftware/ex_css_modules#12]
Following the readme and adding ExCSSModules to the phoenix view block returns the following error:

```
== Compilation error in file lib/phrasing_web/views/error_view.ex ==
** (ArgumentError) expected an Elixir module, got: nil
    (elixir) lib/module.ex:1345: Module.split/2
    (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
    (stdlib) erl_eval.erl:888: :erl_eval.expr_list/6
    (stdlib) erl_eval.erl:411: :erl_eval.expr/5
    (stdlib) erl_eval.erl:888: :erl_eval.expr_list/6
    (stdlib) erl_eval.erl:411: :erl_eval.expr/5
    (stdlib) erl_eval.erl:888: :erl_eval.expr_list/6
    (stdlib) erl_eval.erl:411: :erl_eval.expr/5
    (stdlib) erl_eval.erl:888: :erl_eval.expr_list/6
    (stdlib) erl_eval.erl:411: :erl_eval.expr/5
    (elixir) lib/code.ex:605: Code.eval_quoted/3
    expanding macro: ExCSSModules.View.__using__/1
    lib/phrasing_web/views/error_view.ex:2: PhrasingWeb.ErrorView (module)
    (elixir) expanding macro: Kernel.use/2
    lib/phrasing_web/views/error_view.ex:2: PhrasingWeb.ErrorView (module)
    expanding macro: PhrasingWeb.__using__/1
    lib/phrasing_web/views/error_view.ex:2: PhrasingWeb.ErrorView (module)
    (elixir) expanding macro: Kernel.use/2
    lib/phrasing_web/views/error_view.ex:2: PhrasingWeb.ErrorView (module)
```

Any idea how to fix it?

**Comment by sn3p** [comment]
Sorry for not answering earlier, I totally missed your message :(

The error alone does not reveal to me what is going wrong. Could you share your implementation?
You could also check out this (rather old) example repo as a working example: https://github.com/DefactoSoftware/cells_and_modules
